services:
  - type: web
    name: todo
    env: static
    staticPublishPath: dist/todo
    buildCommand: npm install && npm run build -- --configuration=production
    headers:
      - path: /*
        name: "Cache-Control"
        value: "no-cache"
